"
Les instructions d’affectation de champs pour les instructions pointées de la
forme `abc.def=variable/value`
"
Class {
	#name : #FamixEsopeFieldAssignment,
	#superclass : #FamixEsopeUtilisationSegment,
	#category : #'Famix-Esope-Entities-Entities'
}

{ #category : #meta }
FamixEsopeFieldAssignment class >> annotation [

	<FMClass: #FieldAssignment super: #FamixEsopeUtilisationSegment>
	<package: #'Famix-Esope-Entities'>
	<generated>
	^self
]
