Class {
	#name : #FamixEsopeImportingContext,
	#superclass : #FmxImportingContext,
	#category : #'Famix-Esope-Entities'
}

{ #category : #testing }
FamixEsopeImportingContext >> importAttribute [
	<generated>
	^ self import: FamixEsopeAttribute
]

{ #category : #testing }
FamixEsopeImportingContext >> importEntity [
	<generated>
	^ self import: FamixEsopeEntity
]

{ #category : #testing }
FamixEsopeImportingContext >> importEsoAr [
	<generated>
	^ self import: FamixEsopeEsoAr
]

{ #category : #testing }
FamixEsopeImportingContext >> importEsoAt [
	<generated>
	^ self import: FamixEsopeEsoAt
]

{ #category : #testing }
FamixEsopeImportingContext >> importEsoSl [
	<generated>
	^ self import: FamixEsopeEsoSl
]

{ #category : #testing }
FamixEsopeImportingContext >> importEsopeFunction [
	<generated>
	^ self import: FamixEsopeEsopeFunction
]

{ #category : #testing }
FamixEsopeImportingContext >> importFortranVariable [
	<generated>
	^ self import: FamixEsopeFortranVariable
]

{ #category : #testing }
FamixEsopeImportingContext >> importImplicitPointer [
	<generated>
	^ self import: FamixEsopeImplicitPointer
]

{ #category : #testing }
FamixEsopeImportingContext >> importPointer [
	<generated>
	^ self import: FamixEsopePointer
]

{ #category : #testing }
FamixEsopeImportingContext >> importSegact [
	<generated>
	^ self import: FamixEsopeSegact
]

{ #category : #testing }
FamixEsopeImportingContext >> importSegadj [
	<generated>
	^ self import: FamixEsopeSegadj
]

{ #category : #testing }
FamixEsopeImportingContext >> importSegdes [
	<generated>
	^ self import: FamixEsopeSegdes
]

{ #category : #testing }
FamixEsopeImportingContext >> importSegini [
	<generated>
	^ self import: FamixEsopeSegini
]

{ #category : #testing }
FamixEsopeImportingContext >> importSegment [
	<generated>
	^ self import: FamixEsopeSegment
]

{ #category : #testing }
FamixEsopeImportingContext >> importSegmentUse [
	<generated>
	^ self import: FamixEsopeSegmentUse
]

{ #category : #testing }
FamixEsopeImportingContext >> importSegsup [
	<generated>
	^ self import: FamixEsopeSegsup
]

{ #category : #testing }
FamixEsopeImportingContext >> importUnknown [
	<generated>
	^ self import: FamixEsopeUnknown
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportAttribute [
	<generated>
	^ self shouldImport: FamixEsopeAttribute
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportEntity [
	<generated>
	^ self shouldImport: FamixEsopeEntity
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportEsoAr [
	<generated>
	^ self shouldImport: FamixEsopeEsoAr
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportEsoAt [
	<generated>
	^ self shouldImport: FamixEsopeEsoAt
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportEsoSl [
	<generated>
	^ self shouldImport: FamixEsopeEsoSl
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportEsopeFunction [
	<generated>
	^ self shouldImport: FamixEsopeEsopeFunction
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportFortranVariable [
	<generated>
	^ self shouldImport: FamixEsopeFortranVariable
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportImplicitPointer [
	<generated>
	^ self shouldImport: FamixEsopeImplicitPointer
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportPointer [
	<generated>
	^ self shouldImport: FamixEsopePointer
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportSegact [
	<generated>
	^ self shouldImport: FamixEsopeSegact
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportSegadj [
	<generated>
	^ self shouldImport: FamixEsopeSegadj
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportSegdes [
	<generated>
	^ self shouldImport: FamixEsopeSegdes
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportSegini [
	<generated>
	^ self shouldImport: FamixEsopeSegini
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportSegment [
	<generated>
	^ self shouldImport: FamixEsopeSegment
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportSegmentUse [
	<generated>
	^ self shouldImport: FamixEsopeSegmentUse
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportSegsup [
	<generated>
	^ self shouldImport: FamixEsopeSegsup
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportUnknown [
	<generated>
	^ self shouldImport: FamixEsopeUnknown
]
