Class {
	#name : #FamixEsopeImportingContext,
	#superclass : #FmxImportingContext,
	#category : #'Famix-Esope-Entities'
}

{ #category : #testing }
FamixEsopeImportingContext >> importAccessToDimensions [
	<generated>
	^ self import: FamixEsopeAccessToDimensions
]

{ #category : #testing }
FamixEsopeImportingContext >> importAccessToPointeur [
	<generated>
	^ self import: FamixEsopeAccessToPointeur
]

{ #category : #testing }
FamixEsopeImportingContext >> importAttribute [
	<generated>
	^ self import: FamixEsopeAttribute
]

{ #category : #testing }
FamixEsopeImportingContext >> importComment [
	<generated>
	^ self import: FamixEsopeComment
]

{ #category : #testing }
FamixEsopeImportingContext >> importEntity [
	<generated>
	^ self import: FamixEsopeEntity
]

{ #category : #testing }
FamixEsopeImportingContext >> importFieldAssignment [
	<generated>
	^ self import: FamixEsopeFieldAssignment
]

{ #category : #testing }
FamixEsopeImportingContext >> importImplicitPointeur [
	<generated>
	^ self import: FamixEsopeImplicitPointeur
]

{ #category : #testing }
FamixEsopeImportingContext >> importPointeur [
	<generated>
	^ self import: FamixEsopePointeur
]

{ #category : #testing }
FamixEsopeImportingContext >> importSegAct [
	<generated>
	^ self import: FamixEsopeSegAct
]

{ #category : #testing }
FamixEsopeImportingContext >> importSegAdj [
	<generated>
	^ self import: FamixEsopeSegAdj
]

{ #category : #testing }
FamixEsopeImportingContext >> importSegDes [
	<generated>
	^ self import: FamixEsopeSegDes
]

{ #category : #testing }
FamixEsopeImportingContext >> importSegIni [
	<generated>
	^ self import: FamixEsopeSegIni
]

{ #category : #testing }
FamixEsopeImportingContext >> importSegSup [
	<generated>
	^ self import: FamixEsopeSegSup
]

{ #category : #testing }
FamixEsopeImportingContext >> importSegment [
	<generated>
	^ self import: FamixEsopeSegment
]

{ #category : #testing }
FamixEsopeImportingContext >> importType [
	<generated>
	^ self import: FamixEsopeType
]

{ #category : #testing }
FamixEsopeImportingContext >> importUtilisationSegment [
	<generated>
	^ self import: FamixEsopeUtilisationSegment
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportAccessToDimensions [
	<generated>
	^ self shouldImport: FamixEsopeAccessToDimensions
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportAccessToPointeur [
	<generated>
	^ self shouldImport: FamixEsopeAccessToPointeur
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportAttribute [
	<generated>
	^ self shouldImport: FamixEsopeAttribute
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportComment [
	<generated>
	^ self shouldImport: FamixEsopeComment
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportEntity [
	<generated>
	^ self shouldImport: FamixEsopeEntity
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportFieldAssignment [
	<generated>
	^ self shouldImport: FamixEsopeFieldAssignment
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportImplicitPointeur [
	<generated>
	^ self shouldImport: FamixEsopeImplicitPointeur
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportPointeur [
	<generated>
	^ self shouldImport: FamixEsopePointeur
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportSegAct [
	<generated>
	^ self shouldImport: FamixEsopeSegAct
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportSegAdj [
	<generated>
	^ self shouldImport: FamixEsopeSegAdj
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportSegDes [
	<generated>
	^ self shouldImport: FamixEsopeSegDes
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportSegIni [
	<generated>
	^ self shouldImport: FamixEsopeSegIni
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportSegSup [
	<generated>
	^ self shouldImport: FamixEsopeSegSup
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportSegment [
	<generated>
	^ self shouldImport: FamixEsopeSegment
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportType [
	<generated>
	^ self shouldImport: FamixEsopeType
]

{ #category : #testing }
FamixEsopeImportingContext >> shouldImportUtilisationSegment [
	<generated>
	^ self shouldImport: FamixEsopeUtilisationSegment
]
