Class {
	#name : #FamixEsopeModel,
	#superclass : #MooseModel,
	#category : #'Famix-Esope-Entities-Model'
}

{ #category : #accessing }
FamixEsopeModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits')
]

{ #category : #meta }
FamixEsopeModel class >> annotation [
	<FMClass: #FamixEsopeModel super: #MooseModel>
	<package: #'Famix-Esope-Entities'>
	<generated>
]
