name: generate plantuml

on: [push]

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@master
        with:
          path: data
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
